//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проверочная_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int Код { get; set; }
        public string Название { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Итог { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    }
}
