//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проверочная_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги_
    {
        public int Код { get; set; }
        public Nullable<int> Вид { get; set; }
        public Nullable<int> Автор { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Изображение { get; set; }
    
        public virtual Автор_ Автор_ { get; set; }
        public virtual Вид_ Вид_ { get; set; }
    }
}
